### ISSUE TITLE
Jasper Reports PDF export

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#797]
PDF exporting has stopped working, following error thrown:

Caused by: java.lang.NoSuchMethodError: com.lowagie.text.pdf.PdfWriter.setRgbTransparencyBlending(Z)V
    at net.sf.jasperreports.engine.export.JRPdfExporter.exportReportToStream(JRPdfExporter.java:678)
    at net.sf.jasperreports.engine.export.JRPdfExporter.exportReport(JRPdfExporter.java:513)
    at com.k_int.kbplus.JasperReportsController.generateResponse(JasperReportsController.groovy:132)

Dependency versions is correct (iText 2.1.7), no obvious cause of the problem. Fix this and also change deprecated methods in JasperExportFormat

**Comment by iyawnis** [comment]
This happens because something is pulling itext 2.0.8(after looking at m2 repo)  and I guess it overrides the newer version.

**Comment by iyawnis** [comment]
Fixed on  621fbb450d3ce865fe75145a25585cd68eb007cf
