### ISSUE TITLE
Stacktrace.log issue on live

### ISSUE THREAD

**Issue by ianibo** [k-int/KBPlus#886]
Seeing this issue in stacktrace.log on live:

groovy.lang.MissingPropertyException: No such property: customProperties for class: com.k_int.kbplus.IssueEntitlement
    at com.k_int.kbplus.PendingChangeService.processCustomPropertyChange(PendingChangeService.groovy:147)
    at GrailsMelodyGrailsPlugin$_closure4_closure16_closure17.doCall(GrailsMelodyGrailsPlugin.groovy:184)
    at com.k_int.kbplus.PendingChangeService$_performAccept_closure1.doCall(PendingChangeService.groovy:42)
    at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:815)
    at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:767)
    at org.grails.datastore.gorm.GormStaticApi.withNewTransaction(GormStaticApi.groovy:728)
    at com.k_int.kbplus.PendingChangeService.performAccept(PendingChangeService.groovy:15)
    at GrailsMelodyGrailsPlugin$_closure4_closure16_closure17.doCall(GrailsMelodyGrailsPlugin.groovy:184)
    at com.k_int.kbplus.SubscriptionDetailsController$_index_closure1.doCall(SubscriptionDetailsController.groovy:58)
    at com.k_int.kbplus.SubscriptionDetailsController.index(SubscriptionDetailsController.groovy:57)
    at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
    at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
    at net.bull.javamelody.JspWrapper.invoke(JspWrapper.java:150)
    at net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler.invoke(JdbcWrapper.java:285)
    at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:198)
    at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:176)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by iyawnis** [comment]
Is the debug log available? just above this error should be an output from this line :
                  log.debug("We are dealing with custom properties: ${parsed_change_info}")

**Comment by iyawnis** [comment]
Addressed on 87375a6922ec09baf3158821d7ff449fba49e850 although not sure whats causing this yet..
